/* eslint-disable prettier/prettier */
import {
  StyleSheet,
} from 'react-native';
import {
  ProportionateScreenSizeValue,
} from '../../helper/CommonHelper';
import {
  DefaultInputFontSize,
  DefaultInputHeight,
} from './BasicStyles';

export const BackgroundColor = '#2A2C4E';
const ButtonColor = '#815BF0';

export const RegisterStyles = StyleSheet.create({
  bodyContainerStyle: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: BackgroundColor,
  },
  titleContainerStyle: {
    height: '8%',
    width: '70%',
    paddingLeft: ProportionateScreenSizeValue(15),
    paddingRight: ProportionateScreenSizeValue(15),
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: ProportionateScreenSizeValue(10),
    borderTopRightRadius: ProportionateScreenSizeValue(10),
  },
  titleStyle: {
    color: '#000000',
    fontStyle: 'normal',
    fontSize: ProportionateScreenSizeValue(20),
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  formContainerStyle: {
    height: '72%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
  },
  formContainerContentStyle: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
  },
  formInputContainerStyle: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    width: '100%',
    height: '100%',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: ProportionateScreenSizeValue(10),
  },
  formInputSectionStyle: {
    flexDirection: 'row',
    height: ProportionateScreenSizeValue(40),
    width: '100%',
    marginTop: ProportionateScreenSizeValue(5),
    paddingLeft: ProportionateScreenSizeValue(15),
    paddingRight: ProportionateScreenSizeValue(15),
    justifyContent: 'center',
  },
  bodySectionStyle: {
    flexDirection: 'row',
    height: ProportionateScreenSizeValue(40),
    width: '100%',
    paddingLeft: ProportionateScreenSizeValue(15),
    paddingRight: ProportionateScreenSizeValue(15),
    justifyContent: 'center',
    alignItems: 'center',
  },
  customInputStyle: {
    color: '#000000',
    backgroundColor: '#FFFFFF',
    width: '100%',
    fontSize: ProportionateScreenSizeValue(12),
    borderWidth: ProportionateScreenSizeValue(1),
    height: ProportionateScreenSizeValue(DefaultInputHeight),
    borderRadius: ProportionateScreenSizeValue(10),
    borderColor: '#DDDDDD',
    paddingLeft: ProportionateScreenSizeValue(15),
    paddingRight: ProportionateScreenSizeValue(15),
  },
  dropdownInputContainerStyle: {
    width: '100%',
    height: ProportionateScreenSizeValue(DefaultInputHeight),
    fontSize: ProportionateScreenSizeValue(DefaultInputFontSize),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: ProportionateScreenSizeValue(1),
    borderRadius: ProportionateScreenSizeValue(10),
    borderColor: '#DDDDDD',
  },
  dropdownInputStyle: {
    width: '80%',
    height: '100%',
    paddingLeft: ProportionateScreenSizeValue(15),
    paddingRight: ProportionateScreenSizeValue(15),
    color: '#000',
    fontSize: ProportionateScreenSizeValue(DefaultInputFontSize),
  },
  dropdownResetButtonContainerStyle: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dropdownResetButtonStyle: {
    marginLeft: ProportionateScreenSizeValue(130),
    zIndex: 2,
    width: ProportionateScreenSizeValue(16),
    height: ProportionateScreenSizeValue(16),
    borderRadius: ProportionateScreenSizeValue(8),
    borderWidth: ProportionateScreenSizeValue(1),
    borderColor: 'red',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  dropdownResetButtonTextStyle: {
    fontSize: ProportionateScreenSizeValue(10),
    lineHeight: ProportionateScreenSizeValue(12),
    color: 'red',
    fontWeight: 'bold',
  },
  dropdownButtonContainerStyle: {
    width: '20%',
    height: '70%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderLeftWidth: ProportionateScreenSizeValue(1),
    borderLeftColor: '#CBCBCB',
  },
  dropdownButtonStyle: {
    fontSize: ProportionateScreenSizeValue(8),
  },
  dropdownListMainSectionStyle: {
    width: '90%',
    height: ProportionateScreenSizeValue(300),
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowOpacity: 0.5,
    shadowRadius: ProportionateScreenSizeValue(20),
    shadowColor: '#000',
    elevation: ProportionateScreenSizeValue(20),
  },
  dropdownListViewSectionStyle: {
    width: '100%',
  },
  dropdownListSearchSectionStyle: {
    width: '100%',
    height: ProportionateScreenSizeValue(DefaultInputHeight),
    marginTop: ProportionateScreenSizeValue(10),
    marginBottom: ProportionateScreenSizeValue(10),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dropdownListSearchSectionContainerStyle: {
    width: '90%',
    height: '100%',
    borderWidth: ProportionateScreenSizeValue(1),
    borderColor: '#D1D5E0',
    borderRadius: ProportionateScreenSizeValue(10),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dropdownListSearchInputStyle: {
    width: '80%',
    fontSize: ProportionateScreenSizeValue(12),
    paddingHorizontal: ProportionateScreenSizeValue(10),
  },
  dropdownListSearchButtonStyle: {
    borderLeftWidth: ProportionateScreenSizeValue(1),
    borderColor: '#D1D5E0',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: '70%',
    width: '20%',
  },
  dropdownListViewItemSectionStyle: {
    width: '100%',
    height: ProportionateScreenSizeValue(45),
    padding: ProportionateScreenSizeValue(5),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dropdownListViewItemTextSectionStyle: {
    width: '80%',
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  dropdownListViewItemTextStyle: {
    fontSize: ProportionateScreenSizeValue(12),
  },
  dropdownListButtonSectionStyle: {
    width: '100%',
    height: '25%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dropdownListButtonStyle: {
    width: '50%',
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopWidth: ProportionateScreenSizeValue(1),
    borderTopColor: '#CECECE',
  },
  dropdownListButtonContentStyle: {
    width: '80%',
    height: '60%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dropdownListButtonSelectStyle: {
    backgroundColor: ButtonColor,
  },
  dropdownListButtonCancelStyle: {
    backgroundColor: '#FFF',
    borderWidth: ProportionateScreenSizeValue(1),
    borderColor: ButtonColor,
  },
  dropdownListButtonTextStyle: {
    fontSize: ProportionateScreenSizeValue(12),
  },
  dropdownListButtonSelectTextStyle: {
    color: '#FFF',
  },
  dropdownListButtonCancelTextStyle: {
    fontSize: ProportionateScreenSizeValue(12),
    color: ButtonColor,
  },
  customPasswordInputStyle: {
    fontSize: ProportionateScreenSizeValue(DefaultInputFontSize),
    height: '100%',
    width: '80%',
    color: '#000000',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 0,
  },
  passwordButtonStyle: {
    height: '100%',
    width: '20%',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  passwordButtonTextStyle: {
    fontSize: ProportionateScreenSizeValue(8),
  },
  buttonContainerStyle: {
    height: '20%',
    backgroundColor: '#FFF',
    width: '100%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonSubmitStyle: {
    backgroundColor: '#E37550',
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonSubmitDisableStyle: {
    backgroundColor: 'rgba(227, 117, 80, 0.6)',
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonTextStyle: {
    color: '#FFFFFF',
    paddingVertical: ProportionateScreenSizeValue(8),
    fontStyle: 'normal',
    fontSize: ProportionateScreenSizeValue(14),
    lineHeight: ProportionateScreenSizeValue(17),
  },
  loginContainerStyle: {
    flexDirection: 'row',
    height: ProportionateScreenSizeValue(40),
    width: '100%',
    marginTop: ProportionateScreenSizeValue(10),
    paddingLeft: ProportionateScreenSizeValue(15),
    paddingRight: ProportionateScreenSizeValue(15),
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginTextStyle: {
    color: '#000000',
    textAlign: 'center',
    fontSize: ProportionateScreenSizeValue(12),
  },
  loginTextButtonStyle: {
    color: '#E37550',
    textAlign: 'center',
    fontSize: ProportionateScreenSizeValue(12),
  },
  errorTextStyle: {
    color: '#FF4D05',
    textAlign: 'center',
    fontSize: ProportionateScreenSizeValue(12),
    fontStyle: 'italic',
  },
  techProblemDescStyle: {
    fontSize: ProportionateScreenSizeValue(12),
    lineHeight: ProportionateScreenSizeValue(17),
    color: '#000000',
  },
  techProblemStyle: {
    fontSize: ProportionateScreenSizeValue(12),
    lineHeight: ProportionateScreenSizeValue(17),
    color: '#FF4D05',
    textDecorationLine: 'underline',
  },
  customActivityIndicatorStyle: {
    alignItems: 'center',
    height: '100%',
    width: '100%',
    position: 'absolute',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    zIndex: 99999,
  },
});
