import {
  StyleSheet,
} from 'react-native';

export const UserStyles = StyleSheet.create({
  bodyContainerStyle: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bodyImageStyle: {
    alignItems: 'center',
    marginBottom: 15,
  },
  imageLogoStyle: {
    width: '100%',
    height: 100,
    resizeMode: 'contain',
  },
  bodyWrapperStyle: {
    borderRadius: 15,
    paddingTop: 20,
    paddingBottom: 20,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowColor: 'black',
    shadowOpacity: 0.2,
    width: 300,
  },
  bodySectionTitleStyle: {
    flexDirection: 'row',
    marginTop: 5,
    marginLeft: 15,
    marginRight: 15,
  },
  bodySectionStyle: {
    flexDirection: 'row',
    height: 40,
    marginTop: 5,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 5,
    justifyContent: 'center',
    outlineWidth: 0,
  },
  buttonStyle: {
    backgroundColor: '#E37550',
    borderWidth: 1,
    color: '#FFFFFF',
    borderColor: '#FFFFFF',
    height: 35,
    width: '100%',
    alignItems: 'center',
    borderRadius: 5,
    marginTop: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowColor: 'black',
    shadowOpacity: 0.2,
  },
  buttonTextStyle: {
    color: '#FFFFFF',
    paddingVertical: 8,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 14,
    lineHeight: 17,
  },
  buttonInvertStyle: {
    backgroundColor: '#FAE7E0',
    borderWidth: 1,
    color: '#E37550',
    borderColor: '#E37550',
    height: 35,
    width: '100%',
    alignItems: 'center',
    borderRadius: 5,
    marginTop: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowColor: 'black',
    shadowOpacity: 0.2,
  },
  buttonInvertTextStyle: {
    color: '#E37550',
    paddingVertical: 8,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 14,
    lineHeight: 17,
  },
  errorTextStyle: {
    color: 'red',
    textAlign: 'center',
    fontSize: 14,
    fontStyle: 'italic',
  },
  saveOptionBodySectionStyle: {
    flexDirection: 'row',
    marginTop: 10,
    marginLeft: 15,
    marginRight: 15,
    justifyContent: 'center',
    outlineWidth: 0,
  },
  saveOptionTitleStyle: {
    color: '#FFF',
    paddingVertical: 2,
    fontStyle: 'normal',
    fontSize: 14,
  },
  customActivityIndicatorStyle: {
    alignItems: 'center',
    height: '100%',
    width: '100%',
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    opacity: 0.3,
  },
});