import {
  StyleSheet,
} from 'react-native';

export const LoginStyles = StyleSheet.create({
  bodyContainerStyle: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bodyImageStyle: {
    alignItems: 'center',
    marginBottom: 15,
  },
  imageLogoStyle: {
    width: '100%',
    height: 100,
    resizeMode: 'contain',
  },
  bodyWrapperStyle: {
    borderRadius: 15,
    paddingTop: 20,
    paddingBottom: 20,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowColor: 'black',
    shadowOpacity: 0.2,
    maxWidth: 400,
  },
  bodySectionTitleStyle: {
    flexDirection: 'row',
    marginTop: 5,
    marginLeft: 15,
    marginRight: 15,
  },
  bodySectionStyle: {
    flexDirection: 'row',
    height: 40,
    marginTop: 5,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 5,
    justifyContent: 'center',
    outlineWidth: 0,
  },
  buttonStyle: {
    backgroundColor: '#E37550',
    borderWidth: 1,
    color: '#FFFFFF',
    borderColor: 'white',
    height: 35,
    width: '100%',
    alignItems: 'center',
    borderRadius: 5,
    marginTop: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowColor: 'black',
    shadowOpacity: 0.2,
  },
  buttonTextStyle: {
    color: '#FFFFFF',
    paddingVertical: 8,
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 17,
  },
  forgotPwdTextStyle: {
    color: '#E37550',
    textAlign: 'center',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 17,
    alignSelf: 'center',
    marginTop: 10,
    outlineWidth: 0,
    textDecorationLine: 'underline',
  },
  errorTextStyle: {
    color: 'red',
    textAlign: 'center',
    fontSize: 14,
    fontStyle: 'italic',
  },
  loginWithGoogleStyle: {
    flexDirection: 'row',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: 'white',
    height: 40,
    marginTop: 30,
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    maxWidth: 400,
    backgroundColor: 'rgba(250,231,224,0.8)',
  },
  googleLogoStyle: {
    width: 25,
    height: 25,
    resizeMode: 'contain',
    marginRight: 10,
  },
  loginWithGoogleTextStyle: {
    fontStyle: 'bold',
    fontSize: 14,
    lineHeight: 17,
    color: '#E37550',
    textAlign: 'center',
  },
  techProblemDescStyle: {
    fontStyle: 'normal',
    fontSize: 12,
    lineHeight: 17,
    color: 'white',
    marginTop: 30,
  },
  techProblemStyle: {
    fontStyle: 'bold',
    fontSize: 14,
    lineHeight: 17,
    color: 'maroon',
    cursor: 'pointer',
    outlineWidth: 0,
    textDecorationLine: 'underline',
  },
  customActivityIndicatorStyle: {
    alignItems: 'center',
    height: '100%',
    width: '100%',
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    opacity: 0.3,
  },
});